- id: openhound-cypher-bundle
  name: OpenHound create a cypher query bundle
  entry: scripts/bundle.py
  language: python
  pass_filenames: false

- id: openhound-cypher-test
  name: OpenHound validate cypher query syntax
  entry: pytest tests/test_config_validation.py -q
  language: python
  pass_filenames: false